name: Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Check runner
        run: |
          echo "Hello from self-hosted runner!"
          hostname
          uname -a